#!/bin/zsh

while read connection; do
	password="$(nmcli connection show "$connection" --show-secrets | grep '^802-11-wireless-security\.psk:' | awk '{ print $2 }')"
	if [[ -n "$password" ]]; then
		echo $connection
		echo $password
		echo ''
	fi
done < <(nmcli connection show | awk 'BEGIN { FIELDWIDTHS = "34 38 11 10" }
	NR > 1 {
		name = $1
		type = $3

		sub(/ +$/, "", name)
		sub(/ +$/, "", type)

		if (type == "wifi")
			print name
	}')
