#!/bin/bash

swaymsg -t get_tree \
	| jq -r '.nodes[].nodes[] | select(.name == "__i3_scratch") | .floating_nodes.[] | ((.id | tostring) + " " + .name)' \
	| wofi --prompt "Scratchpad" --show dmenu \
	| {
		read -r id name
		swaymsg "[con_id=$id]" focus
	}
